PRODUCT_COPY_FILES += \
    vendor/xiaomi/ugglite/camera/vendor/etc/camera/camera_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/camera_config.xml \
    vendor/xiaomi/ugglite/camera/vendor/etc/camera/csidtg_camera.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/csidtg_camera.xml \
    vendor/xiaomi/ugglite/camera/vendor/etc/camera/csidtg_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/csidtg_chromatix.xml \
    vendor/xiaomi/ugglite/camera/vendor/etc/camera/imx214_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/imx214_chromatix.xml \
    vendor/xiaomi/ugglite/camera/vendor/etc/camera/imx230_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/imx230_chromatix.xml \
    vendor/xiaomi/ugglite/camera/vendor/etc/camera/imx230_qc2002_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/imx230_qc2002_chromatix.xml \
    vendor/xiaomi/ugglite/camera/vendor/etc/camera/imx230_qc2002_with_gyro_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/imx230_qc2002_with_gyro_chromatix.xml \
    vendor/xiaomi/ugglite/camera/vendor/etc/camera/imx258_bear_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/imx258_bear_chromatix.xml \
    vendor/xiaomi/ugglite/camera/vendor/etc/camera/imx258_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/imx258_chromatix.xml \
    vendor/xiaomi/ugglite/camera/vendor/etc/camera/imx258_mono_bear_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/imx258_mono_bear_chromatix.xml \
    vendor/xiaomi/ugglite/camera/vendor/etc/camera/imx258_mono_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/imx258_mono_chromatix.xml \
    vendor/xiaomi/ugglite/camera/vendor/etc/camera/imx298_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/imx298_chromatix.xml \
    vendor/xiaomi/ugglite/camera/vendor/etc/camera/imx298_gt24c64_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/imx298_gt24c64_chromatix.xml \
    vendor/xiaomi/ugglite/camera/vendor/etc/camera/imx318_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/imx318_chromatix.xml \
    vendor/xiaomi/ugglite/camera/vendor/etc/camera/imx362_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/imx362_chromatix.xml \
    vendor/xiaomi/ugglite/camera/vendor/etc/camera/imx362_chromatix_bear.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/imx362_chromatix_bear.xml \
    vendor/xiaomi/ugglite/camera/vendor/etc/camera/imx378_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/imx378_chromatix.xml \
    vendor/xiaomi/ugglite/camera/vendor/etc/camera/ov12a10_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/ov12a10_chromatix.xml \
    vendor/xiaomi/ugglite/camera/vendor/etc/camera/ov13850_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/ov13850_chromatix.xml \
    vendor/xiaomi/ugglite/camera/vendor/etc/camera/ov13850_q13v06k_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/ov13850_q13v06k_chromatix.xml \
    vendor/xiaomi/ugglite/camera/vendor/etc/camera/ov13855_d6_qtich_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/ov13855_d6_qtich_chromatix.xml \
    vendor/xiaomi/ugglite/camera/vendor/etc/camera/ov13855_f13855bd_qtech_d6_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/ov13855_f13855bd_qtech_d6_chromatix.xml \
    vendor/xiaomi/ugglite/camera/vendor/etc/camera/ov13855_f13855bd_qtech_d6s_chromatix_india.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/ov13855_f13855bd_qtech_d6s_chromatix_india.xml \
    vendor/xiaomi/ugglite/camera/vendor/etc/camera/ov16885_ojf0541_d6_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/ov16885_ojf0541_d6_chromatix.xml \
    vendor/xiaomi/ugglite/camera/vendor/etc/camera/ov16885_ojf0541_ofilm_d7_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/ov16885_ojf0541_ofilm_d7_chromatix.xml \
    vendor/xiaomi/ugglite/camera/vendor/etc/camera/ov2281_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/ov2281_chromatix.xml \
    vendor/xiaomi/ugglite/camera/vendor/etc/camera/ov2680_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/ov2680_chromatix.xml \
    vendor/xiaomi/ugglite/camera/vendor/etc/camera/ov4688_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/ov4688_chromatix.xml \
    vendor/xiaomi/ugglite/camera/vendor/etc/camera/ov5670_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/ov5670_chromatix.xml \
    vendor/xiaomi/ugglite/camera/vendor/etc/camera/ov5670_f5670bq_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/ov5670_f5670bq_chromatix.xml \
    vendor/xiaomi/ugglite/camera/vendor/etc/camera/ov5695_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/ov5695_chromatix.xml \
    vendor/xiaomi/ugglite/camera/vendor/etc/camera/ov7251_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/ov7251_chromatix.xml \
    vendor/xiaomi/ugglite/camera/vendor/etc/camera/ov8858_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/ov8858_chromatix.xml \
    vendor/xiaomi/ugglite/camera/vendor/etc/camera/ov8865_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/ov8865_chromatix.xml \
    vendor/xiaomi/ugglite/camera/vendor/etc/camera/s5k2l7_8953_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/s5k2l7_8953_chromatix.xml \
    vendor/xiaomi/ugglite/camera/vendor/etc/camera/s5k2l7_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/s5k2l7_chromatix.xml \
    vendor/xiaomi/ugglite/camera/vendor/etc/camera/s5k2p7_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/s5k2p7_chromatix.xml \
    vendor/xiaomi/ugglite/camera/vendor/etc/camera/s5k2p7_ulysse_semco_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/s5k2p7_ulysse_semco_chromatix.xml \
    vendor/xiaomi/ugglite/camera/vendor/etc/camera/s5k3l8_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/s5k3l8_chromatix.xml \
    vendor/xiaomi/ugglite/camera/vendor/etc/camera/s5k3l8_f13s10m_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/s5k3l8_f13s10m_chromatix.xml \
    vendor/xiaomi/ugglite/camera/vendor/etc/camera/s5k3l8_f3l8yam_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/s5k3l8_f3l8yam_chromatix.xml \
    vendor/xiaomi/ugglite/camera/vendor/etc/camera/s5k3l8_mono_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/s5k3l8_mono_chromatix.xml \
    vendor/xiaomi/ugglite/camera/vendor/etc/camera/s5k3l8_ohp0502_ofilm_d6_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/s5k3l8_ohp0502_ofilm_d6_chromatix.xml \
    vendor/xiaomi/ugglite/camera/vendor/etc/camera/s5k3l8_ohp0502_ofilm_d6_chromatix_india.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/s5k3l8_ohp0502_ofilm_d6_chromatix_india.xml \
    vendor/xiaomi/ugglite/camera/vendor/etc/camera/s5k3m2xm_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/s5k3m2xm_chromatix.xml \
    vendor/xiaomi/ugglite/camera/vendor/etc/camera/s5k3m2xm_chromatix_bear.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/s5k3m2xm_chromatix_bear.xml \
    vendor/xiaomi/ugglite/camera/vendor/etc/camera/s5k3m2xx_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/s5k3m2xx_chromatix.xml \
    vendor/xiaomi/ugglite/camera/vendor/etc/camera/s5k3p3sm_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/s5k3p3sm_chromatix.xml \
    vendor/xiaomi/ugglite/camera/vendor/etc/camera/s5k3p3st_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/s5k3p3st_chromatix.xml \
    vendor/xiaomi/ugglite/camera/vendor/etc/camera/s5k3p8_ofilm_d3_factory_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/s5k3p8_ofilm_d3_factory_chromatix.xml \
    vendor/xiaomi/ugglite/camera/vendor/etc/camera/s5k3p8_sunny_d3_factory_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/s5k3p8_sunny_d3_factory_chromatix.xml \
    vendor/xiaomi/ugglite/camera/vendor/etc/camera/s5k3p8_ulysse_ofilm_black_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/s5k3p8_ulysse_ofilm_black_chromatix.xml \
    vendor/xiaomi/ugglite/camera/vendor/etc/camera/s5k3p8_ulysse_sunny_black_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/s5k3p8_ulysse_sunny_black_chromatix.xml \
    vendor/xiaomi/ugglite/camera/vendor/etc/camera/s5k3p8_ulysse_sunny_white_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/s5k3p8_ulysse_sunny_white_chromatix.xml \
    vendor/xiaomi/ugglite/camera/vendor/etc/camera/s5k3p8sp_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/s5k3p8sp_chromatix.xml \
    vendor/xiaomi/ugglite/camera/vendor/etc/camera/s5k3p8sp_d16s01n_sunny_d6s_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/s5k3p8sp_d16s01n_sunny_d6s_chromatix.xml \
    vendor/xiaomi/ugglite/camera/vendor/etc/camera/s5k3p8sp_d16s01n_sunny_d6s_chromatix_india.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/s5k3p8sp_d16s01n_sunny_d6s_chromatix_india.xml \
    vendor/xiaomi/ugglite/camera/vendor/etc/camera/s5k3p8sp_d16s01n_sunny_d7_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/s5k3p8sp_d16s01n_sunny_d7_chromatix.xml \
    vendor/xiaomi/ugglite/camera/vendor/etc/camera/s5k5e8_f5e8ybf_qtech_d6_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/s5k5e8_f5e8ybf_qtech_d6_chromatix.xml \
    vendor/xiaomi/ugglite/camera/vendor/etc/camera/s5k5e8_f5e8ybf_qtech_d6_chromatix_india.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/s5k5e8_f5e8ybf_qtech_d6_chromatix_india.xml \
    vendor/xiaomi/ugglite/camera/vendor/etc/camera/s5k5e8_oef0501_ofilm_d6_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/s5k5e8_oef0501_ofilm_d6_chromatix.xml \
    vendor/xiaomi/ugglite/camera/vendor/etc/camera/s5k5e8_oef0501_ofilm_d6_chromatix_india.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/s5k5e8_oef0501_ofilm_d6_chromatix_india.xml \
    vendor/xiaomi/ugglite/camera/vendor/lib/libactuator_dw9714.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_dw9714.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libactuator_fp5510_f13855bd.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_fp5510_f13855bd.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_ov13855_f13855ab_default_preview_dw9714a.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov13855_f13855ab_default_preview_dw9714a.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_ov13855_f13855ab_default_video_dw9714a.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov13855_f13855ab_default_video_dw9714a.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_ov13855_f13855ab_hfr_120_dw9714a.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov13855_f13855ab_hfr_120_dw9714a.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_ov13855_f13855ab_hfr_60_dw9714a.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov13855_f13855ab_hfr_60_dw9714a.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_ov13855_f13855ab_hfr_90_dw9714a.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov13855_f13855ab_hfr_90_dw9714a.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_ov13855_f13855ab_zsl_preview_dw9714a.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov13855_f13855ab_zsl_preview_dw9714a.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_ov13855_f13855ab_zsl_video_dw9714a.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov13855_f13855ab_zsl_video_dw9714a.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_ov13855_f13855bd_qtech_d6_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov13855_f13855bd_qtech_d6_common.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_ov13855_f13855bd_qtech_d6_cpp_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov13855_f13855bd_qtech_d6_cpp_hfr_120.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_ov13855_f13855bd_qtech_d6_cpp_hfr_60.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov13855_f13855bd_qtech_d6_cpp_hfr_60.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_ov13855_f13855bd_qtech_d6_cpp_hfr_90.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov13855_f13855bd_qtech_d6_cpp_hfr_90.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_ov13855_f13855bd_qtech_d6_cpp_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov13855_f13855bd_qtech_d6_cpp_liveshot.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_ov13855_f13855bd_qtech_d6_cpp_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov13855_f13855bd_qtech_d6_cpp_preview.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_ov13855_f13855bd_qtech_d6_cpp_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov13855_f13855bd_qtech_d6_cpp_snapshot.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_ov13855_f13855bd_qtech_d6_cpp_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov13855_f13855bd_qtech_d6_cpp_video.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_ov13855_f13855bd_qtech_d6_cpp_weixin.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov13855_f13855bd_qtech_d6_cpp_weixin.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_ov13855_f13855bd_qtech_d6_default_preview_dw9714.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov13855_f13855bd_qtech_d6_default_preview_dw9714.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_ov13855_f13855bd_qtech_d6_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov13855_f13855bd_qtech_d6_default_video.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_ov13855_f13855bd_qtech_d6_default_video_dw9714.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov13855_f13855bd_qtech_d6_default_video_dw9714.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_ov13855_f13855bd_qtech_d6_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov13855_f13855bd_qtech_d6_hfr_120.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_ov13855_f13855bd_qtech_d6_hfr_120_dw9714.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov13855_f13855bd_qtech_d6_hfr_120_dw9714.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_ov13855_f13855bd_qtech_d6_hfr_60.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov13855_f13855bd_qtech_d6_hfr_60.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_ov13855_f13855bd_qtech_d6_hfr_60_dw9714.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov13855_f13855bd_qtech_d6_hfr_60_dw9714.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_ov13855_f13855bd_qtech_d6_hfr_90.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov13855_f13855bd_qtech_d6_hfr_90.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_ov13855_f13855bd_qtech_d6_hfr_90_dw9714.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov13855_f13855bd_qtech_d6_hfr_90_dw9714.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_ov13855_f13855bd_qtech_d6_postproc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov13855_f13855bd_qtech_d6_postproc.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_ov13855_f13855bd_qtech_d6_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov13855_f13855bd_qtech_d6_preview.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_ov13855_f13855bd_qtech_d6_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov13855_f13855bd_qtech_d6_snapshot.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_ov13855_f13855bd_qtech_d6_zsl_preview_dw9714.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov13855_f13855bd_qtech_d6_zsl_preview_dw9714.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_ov13855_f13855bd_qtech_d6_zsl_video_dw9714.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov13855_f13855bd_qtech_d6_zsl_video_dw9714.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_ov13855_f13855bd_qtech_d6s_india_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov13855_f13855bd_qtech_d6s_india_common.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_ov13855_f13855bd_qtech_d6s_india_cpp_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov13855_f13855bd_qtech_d6s_india_cpp_hfr_120.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_ov13855_f13855bd_qtech_d6s_india_cpp_hfr_60.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov13855_f13855bd_qtech_d6s_india_cpp_hfr_60.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_ov13855_f13855bd_qtech_d6s_india_cpp_hfr_90.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov13855_f13855bd_qtech_d6s_india_cpp_hfr_90.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_ov13855_f13855bd_qtech_d6s_india_cpp_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov13855_f13855bd_qtech_d6s_india_cpp_liveshot.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_ov13855_f13855bd_qtech_d6s_india_cpp_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov13855_f13855bd_qtech_d6s_india_cpp_preview.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_ov13855_f13855bd_qtech_d6s_india_cpp_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov13855_f13855bd_qtech_d6s_india_cpp_snapshot.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_ov13855_f13855bd_qtech_d6s_india_cpp_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov13855_f13855bd_qtech_d6s_india_cpp_video.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_ov13855_f13855bd_qtech_d6s_india_cpp_weixin.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov13855_f13855bd_qtech_d6s_india_cpp_weixin.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_ov13855_f13855bd_qtech_d6s_india_default_preview_dw9714.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov13855_f13855bd_qtech_d6s_india_default_preview_dw9714.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_ov13855_f13855bd_qtech_d6s_india_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov13855_f13855bd_qtech_d6s_india_default_video.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_ov13855_f13855bd_qtech_d6s_india_default_video_dw9714.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov13855_f13855bd_qtech_d6s_india_default_video_dw9714.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_ov13855_f13855bd_qtech_d6s_india_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov13855_f13855bd_qtech_d6s_india_hfr_120.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_ov13855_f13855bd_qtech_d6s_india_hfr_120_dw9714.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov13855_f13855bd_qtech_d6s_india_hfr_120_dw9714.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_ov13855_f13855bd_qtech_d6s_india_hfr_60.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov13855_f13855bd_qtech_d6s_india_hfr_60.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_ov13855_f13855bd_qtech_d6s_india_hfr_60_dw9714.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov13855_f13855bd_qtech_d6s_india_hfr_60_dw9714.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_ov13855_f13855bd_qtech_d6s_india_hfr_90.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov13855_f13855bd_qtech_d6s_india_hfr_90.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_ov13855_f13855bd_qtech_d6s_india_hfr_90_dw9714.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov13855_f13855bd_qtech_d6s_india_hfr_90_dw9714.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_ov13855_f13855bd_qtech_d6s_india_postproc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov13855_f13855bd_qtech_d6s_india_postproc.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_ov13855_f13855bd_qtech_d6s_india_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov13855_f13855bd_qtech_d6s_india_preview.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_ov13855_f13855bd_qtech_d6s_india_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov13855_f13855bd_qtech_d6s_india_snapshot.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_ov13855_f13855bd_qtech_d6s_india_zsl_preview_dw9714.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov13855_f13855bd_qtech_d6s_india_zsl_preview_dw9714.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_ov13855_f13855bd_qtech_d6s_india_zsl_video_dw9714.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov13855_f13855bd_qtech_d6s_india_zsl_video_dw9714.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_ov8865_default_preview_dw9714.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_default_preview_dw9714.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_ov8865_default_video_dw9714.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_default_video_dw9714.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_ov8865_hfr_120_dw9714.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_hfr_120_dw9714.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_ov8865_hfr_60_dw9714.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_hfr_60_dw9714.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_ov8865_hfr_90_dw9714.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_hfr_90_dw9714.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k3l8_ohp0502_ofilm_d6_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_ohp0502_ofilm_d6_common.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k3l8_ohp0502_ofilm_d6_cpp_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_ohp0502_ofilm_d6_cpp_hfr_120.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k3l8_ohp0502_ofilm_d6_cpp_hfr_60.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_ohp0502_ofilm_d6_cpp_hfr_60.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k3l8_ohp0502_ofilm_d6_cpp_hfr_90.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_ohp0502_ofilm_d6_cpp_hfr_90.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k3l8_ohp0502_ofilm_d6_cpp_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_ohp0502_ofilm_d6_cpp_liveshot.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k3l8_ohp0502_ofilm_d6_cpp_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_ohp0502_ofilm_d6_cpp_preview.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k3l8_ohp0502_ofilm_d6_cpp_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_ohp0502_ofilm_d6_cpp_snapshot.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k3l8_ohp0502_ofilm_d6_cpp_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_ohp0502_ofilm_d6_cpp_video.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k3l8_ohp0502_ofilm_d6_cpp_weixin.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_ohp0502_ofilm_d6_cpp_weixin.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k3l8_ohp0502_ofilm_d6_default_preview_dw9714.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_ohp0502_ofilm_d6_default_preview_dw9714.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k3l8_ohp0502_ofilm_d6_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_ohp0502_ofilm_d6_default_video.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k3l8_ohp0502_ofilm_d6_default_video_dw9714.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_ohp0502_ofilm_d6_default_video_dw9714.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k3l8_ohp0502_ofilm_d6_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_ohp0502_ofilm_d6_hfr_120.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k3l8_ohp0502_ofilm_d6_hfr_120_dw9714.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_ohp0502_ofilm_d6_hfr_120_dw9714.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k3l8_ohp0502_ofilm_d6_hfr_60.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_ohp0502_ofilm_d6_hfr_60.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k3l8_ohp0502_ofilm_d6_hfr_60_dw9714.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_ohp0502_ofilm_d6_hfr_60_dw9714.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k3l8_ohp0502_ofilm_d6_hfr_90.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_ohp0502_ofilm_d6_hfr_90.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k3l8_ohp0502_ofilm_d6_hfr_90_dw9714.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_ohp0502_ofilm_d6_hfr_90_dw9714.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k3l8_ohp0502_ofilm_d6_india_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_ohp0502_ofilm_d6_india_common.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k3l8_ohp0502_ofilm_d6_india_cpp_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_ohp0502_ofilm_d6_india_cpp_hfr_120.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k3l8_ohp0502_ofilm_d6_india_cpp_hfr_60.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_ohp0502_ofilm_d6_india_cpp_hfr_60.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k3l8_ohp0502_ofilm_d6_india_cpp_hfr_90.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_ohp0502_ofilm_d6_india_cpp_hfr_90.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k3l8_ohp0502_ofilm_d6_india_cpp_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_ohp0502_ofilm_d6_india_cpp_liveshot.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k3l8_ohp0502_ofilm_d6_india_cpp_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_ohp0502_ofilm_d6_india_cpp_preview.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k3l8_ohp0502_ofilm_d6_india_cpp_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_ohp0502_ofilm_d6_india_cpp_snapshot.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k3l8_ohp0502_ofilm_d6_india_cpp_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_ohp0502_ofilm_d6_india_cpp_video.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k3l8_ohp0502_ofilm_d6_india_cpp_weixin.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_ohp0502_ofilm_d6_india_cpp_weixin.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k3l8_ohp0502_ofilm_d6_india_default_preview_dw9714.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_ohp0502_ofilm_d6_india_default_preview_dw9714.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k3l8_ohp0502_ofilm_d6_india_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_ohp0502_ofilm_d6_india_default_video.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k3l8_ohp0502_ofilm_d6_india_default_video_dw9714.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_ohp0502_ofilm_d6_india_default_video_dw9714.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k3l8_ohp0502_ofilm_d6_india_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_ohp0502_ofilm_d6_india_hfr_120.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k3l8_ohp0502_ofilm_d6_india_hfr_120_dw9714.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_ohp0502_ofilm_d6_india_hfr_120_dw9714.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k3l8_ohp0502_ofilm_d6_india_hfr_60.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_ohp0502_ofilm_d6_india_hfr_60.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k3l8_ohp0502_ofilm_d6_india_hfr_60_dw9714.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_ohp0502_ofilm_d6_india_hfr_60_dw9714.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k3l8_ohp0502_ofilm_d6_india_hfr_90.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_ohp0502_ofilm_d6_india_hfr_90.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k3l8_ohp0502_ofilm_d6_india_hfr_90_dw9714.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_ohp0502_ofilm_d6_india_hfr_90_dw9714.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k3l8_ohp0502_ofilm_d6_india_postproc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_ohp0502_ofilm_d6_india_postproc.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k3l8_ohp0502_ofilm_d6_india_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_ohp0502_ofilm_d6_india_preview.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k3l8_ohp0502_ofilm_d6_india_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_ohp0502_ofilm_d6_india_snapshot.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k3l8_ohp0502_ofilm_d6_india_zsl_preview_dw9714.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_ohp0502_ofilm_d6_india_zsl_preview_dw9714.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k3l8_ohp0502_ofilm_d6_india_zsl_video_dw9714.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_ohp0502_ofilm_d6_india_zsl_video_dw9714.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k3l8_ohp0502_ofilm_d6_postproc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_ohp0502_ofilm_d6_postproc.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k3l8_ohp0502_ofilm_d6_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_ohp0502_ofilm_d6_preview.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k3l8_ohp0502_ofilm_d6_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_ohp0502_ofilm_d6_snapshot.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k3l8_ohp0502_ofilm_d6_zsl_preview_dw9714.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_ohp0502_ofilm_d6_zsl_preview_dw9714.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k3l8_ohp0502_ofilm_d6_zsl_video_dw9714.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_ohp0502_ofilm_d6_zsl_video_dw9714.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_1080p.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_1080p.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_1080p_preview_3a.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_1080p_preview_3a.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_1080p_video_3a.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_1080p_video_3a.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_common.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_cpp_1080p.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_cpp_1080p.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_cpp_fullsize.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_cpp_fullsize.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_cpp_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_cpp_hfr_120.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_cpp_hfr_60_fullsize.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_cpp_hfr_60_fullsize.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_cpp_hfr_90.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_cpp_hfr_90.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_cpp_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_cpp_liveshot.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_cpp_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_cpp_preview.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_cpp_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_cpp_video.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_cpp_weixin.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_cpp_weixin.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_default_preview_3a.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_default_preview_3a.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_default_video.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_default_video_3a.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_default_video_3a.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_fullsize.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_fullsize.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_fullsize_preview_3a.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_fullsize_preview_3a.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_fullsize_video_3a.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_fullsize_video_3a.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_hfr_120.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_hfr_120_3a.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_hfr_120_3a.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_hfr_60.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_hfr_60.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_hfr_60_fullsize_3a.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_hfr_60_fullsize_3a.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_hfr_90.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_hfr_90.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_hfr_90_3a.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_hfr_90_3a.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_india_1080p.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_india_1080p.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_india_1080p_preview_3a.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_india_1080p_preview_3a.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_india_1080p_video_3a.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_india_1080p_video_3a.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_india_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_india_common.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_india_cpp_1080p.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_india_cpp_1080p.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_india_cpp_fullsize.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_india_cpp_fullsize.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_india_cpp_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_india_cpp_hfr_120.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_india_cpp_hfr_60_fullsize.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_india_cpp_hfr_60_fullsize.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_india_cpp_hfr_90.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_india_cpp_hfr_90.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_india_cpp_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_india_cpp_liveshot.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_india_cpp_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_india_cpp_preview.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_india_cpp_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_india_cpp_video.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_india_cpp_weixin.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_india_cpp_weixin.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_india_default_preview_3a.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_india_default_preview_3a.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_india_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_india_default_video.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_india_default_video_3a.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_india_default_video_3a.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_india_fullsize.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_india_fullsize.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_india_fullsize_preview_3a.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_india_fullsize_preview_3a.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_india_fullsize_video_3a.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_india_fullsize_video_3a.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_india_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_india_hfr_120.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_india_hfr_120_3a.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_india_hfr_120_3a.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_india_hfr_60.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_india_hfr_60.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_india_hfr_60_fullsize_3a.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_india_hfr_60_fullsize_3a.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_india_hfr_90.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_india_hfr_90.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_india_hfr_90_3a.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_india_hfr_90_3a.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_india_postproc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_india_postproc.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_india_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_india_preview.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_india_weixin_preview_3a.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_india_weixin_preview_3a.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_india_weixin_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_india_weixin_video.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_postproc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_postproc.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_preview.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_weixin_preview_3a.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_weixin_preview_3a.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_weixin_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_f5e8ybf_qtech_d6_weixin_video.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_1080p.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_1080p.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_1080p_preview_3a.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_1080p_preview_3a.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_1080p_video_3a.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_1080p_video_3a.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_common.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_cpp_1080p.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_cpp_1080p.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_cpp_fullsize.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_cpp_fullsize.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_cpp_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_cpp_hfr_120.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_cpp_hfr_60_fullsize.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_cpp_hfr_60_fullsize.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_cpp_hfr_90.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_cpp_hfr_90.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_cpp_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_cpp_liveshot.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_cpp_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_cpp_preview.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_cpp_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_cpp_video.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_cpp_weixin.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_cpp_weixin.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_default_preview_3a.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_default_preview_3a.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_default_video.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_default_video_3a.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_default_video_3a.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_fullsize.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_fullsize.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_fullsize_preview_3a.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_fullsize_preview_3a.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_fullsize_video_3a.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_fullsize_video_3a.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_hfr_120.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_hfr_120_3a.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_hfr_120_3a.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_hfr_60.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_hfr_60.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_hfr_60_fullsize_3a.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_hfr_60_fullsize_3a.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_hfr_90.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_hfr_90.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_hfr_90_3a.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_hfr_90_3a.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_india_1080p.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_india_1080p.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_india_1080p_preview_3a.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_india_1080p_preview_3a.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_india_1080p_video_3a.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_india_1080p_video_3a.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_india_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_india_common.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_india_cpp_1080p.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_india_cpp_1080p.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_india_cpp_fullsize.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_india_cpp_fullsize.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_india_cpp_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_india_cpp_hfr_120.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_india_cpp_hfr_60_fullsize.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_india_cpp_hfr_60_fullsize.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_india_cpp_hfr_90.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_india_cpp_hfr_90.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_india_cpp_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_india_cpp_liveshot.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_india_cpp_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_india_cpp_preview.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_india_cpp_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_india_cpp_video.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_india_cpp_weixin.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_india_cpp_weixin.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_india_default_preview_3a.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_india_default_preview_3a.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_india_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_india_default_video.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_india_default_video_3a.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_india_default_video_3a.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_india_fullsize.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_india_fullsize.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_india_fullsize_preview_3a.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_india_fullsize_preview_3a.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_india_fullsize_video_3a.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_india_fullsize_video_3a.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_india_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_india_hfr_120.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_india_hfr_120_3a.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_india_hfr_120_3a.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_india_hfr_60.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_india_hfr_60.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_india_hfr_60_fullsize_3a.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_india_hfr_60_fullsize_3a.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_india_hfr_90.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_india_hfr_90.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_india_hfr_90_3a.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_india_hfr_90_3a.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_india_postproc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_india_postproc.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_india_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_india_preview.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_india_weixin_preview_3a.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_india_weixin_preview_3a.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_india_weixin_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_india_weixin_video.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_postproc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_postproc.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_preview.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_weixin_preview_3a.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_weixin_preview_3a.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_weixin_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_oef0501_ofilm_d6_weixin_video.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libmmcamera2_sensor_modules.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_sensor_modules.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libmmcamera_ov13855_f13855bd_d6.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_ov13855_f13855bd_d6.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libmmcamera_ov13855_f13855bd_qtech_eeprom.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_ov13855_f13855bd_qtech_eeprom.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libmmcamera_s5k3l8_ohp0502_d6.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_s5k3l8_ohp0502_d6.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libmmcamera_s5k3l8_ohp0502_d6s.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_s5k3l8_ohp0502_d6s.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libmmcamera_s5k3l8_ohp0502_ofilm_eeprom.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_s5k3l8_ohp0502_ofilm_eeprom.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libmmcamera_s5k5e8_f5e8ybf_d6.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_s5k5e8_f5e8ybf_d6.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libmmcamera_s5k5e8_f5e8ybf_qtech_eeprom.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_s5k5e8_f5e8ybf_qtech_eeprom.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libmmcamera_s5k5e8_oef0501_d6.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_s5k5e8_oef0501_d6.so \
    vendor/xiaomi/ugglite/camera/vendor/lib/libmmcamera_s5k5e8_oef0501_ofilm_eeprom.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_s5k5e8_oef0501_ofilm_eeprom.so
